Add docker.ubuntu role
smartcat-labs/smartcat-ops pull request #88
Opened 2017-03-17 10:43 UTC by narezina

2017-03-17 10:46 UTC, mgobec commented on roles/docker.ubuntu/tasks/main.yml
> +  when: ansible_lsb.id|lower == "ubuntu" and ( ansible_distribution_version|version_compare('12.04', '<') or ansible_distribution_version|version_compare('12.10', '=') )
This should be <= 12.10

2017-03-24 13:37 UTC, nivancevic requested changes

2017-03-24 13:37 UTC, nivancevic commented on roles/docker.ubuntu/defaults/main.yml
> +ssh_port: 22
Too generic name. A prefix should be added?

2017-03-24 13:37 UTC, nivancevic commented on roles/docker.ubuntu/defaults/main.yml
> +ssh_port: 22
Also, Ubuntu versions lower than 14.04 don't need to be supported.

2017-03-24 13:37 UTC, nivancevic commented on roles/docker.ubuntu/defaults/main.yml
> +docker_group_members: []
User 'ubuntu' can be added to the docker system group.

2017-03-24 13:37 UTC, nivancevic commented on roles/docker.ubuntu/tasks/main.yml
> +- name: Start docker
This can be removed if the docker package name is known (Ubuntu 14.04 +).

2017-03-24 13:37 UTC, nivancevic commented on roles/docker.ubuntu/tasks/main.yml
> +- name: Install docker package
Can anything be done in order to install the latest docker version?
For example, manually setting apt-get (https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-16-04) to fetch the latest version.

2017-03-24 21:29 UTC, merged